### PR TITLE
Fixing issue #14 (sonic-pi-cli on Windows 10)

### LINKED ISSUE #14: sonic-pi-cli on Windows 10
I have recently been trying to get the gem to work with the release version of Sonic Pi 2.11 on Windows 10. SP is running fine, and the server log file says
```
Sonic Pi server booting...
Using protocol: udp
Detecting port numbers...
Send port: 4558
Listen port: 4557
  - OK
Scsynth port: 4556
  - OK
Scsynth send port: 4556
  - OK
OSC cues port: 4559
  - OK
Booting server...
```
so port 4557 seems to be open ok. However when I run sonic_pi it give the error
```
Sonic Pi is not listening on 4557 - is it running?
```
Any ideas? It works perfectly on a Mac with SP 2.11

### PR DESCRIPTION
**Pull request by davidair**
Closes #14

### CODE REVIEW

**Comment by Widdershin** [comment]
I'll test this on my Linux install when I get home in ~8 hours, and then happy to merge.

Thanks for sorting this out 😺!

**Comment by davidair** [comment]
I tested on Windows 10 and it's working (note that to make the test work, I had to change "require sonic_pi" in bin/sonic_pi to "require_relative '../lib/sonic_pi'")

**Comment by Widdershin** [comment]
Cool, I still need to test on Linux, forgot to do so last night, will try and do so tonight.

**Comment by davidair** [comment]
Great! Also, I've re-tested on macOS because I realized my original test still used the prod library, not my local one.

**Comment by Widdershin** [comment]
Works great on Linux!

**Comment by Widdershin** [comment]
Released in v0.1.1.

Thanks again for this pull request and your testing @davidair! :smiley_cat:

**Pull request merged**
